export {default as Intro} from "./Intro.service"
export {default as Consult} from "./Consulting.service"
export {default as Data} from "./Data.service"
export {default as Strategy} from "./Strategy.service"
export {default as OtherServices} from "./Other.service"
export {default as Benefits} from "./Benefits.service"
export {default as Experience} from "./Experience.service"